"""initial_schema"""

from alembic import op
import sqlalchemy as sa

revision = "1dc0257e8803"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("max_minutes", sa.Integer(), nullable=False),
        sa.Column("max_concurrent", sa.Integer(), nullable=False),
        sa.Column("used_minutes", sa.Integer(), nullable=False),
        sa.Column("active_sessions", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_buckets",
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("window", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "async_jobs",
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=100), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    with op.batch_alter_table("async_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_async_jobs_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_async_jobs_status"), ["status"], unique=False)
        batch_op.create_index("ix_jobs_ready", ["status", "available_at"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_org_id"), ["org_id"], unique=False)

    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=True),
        sa.Column("application_id", sa.String(length=36), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("csrf", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "candidates",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "email"),
    )
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_candidates_org_id"), ["org_id"], unique=False)

    op.create_table(
        "email_deliveries",
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("payload_ciphertext", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(length=200), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=100), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    with op.batch_alter_table("email_deliveries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_email_deliveries_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_deliveries_provider_id"), ["provider_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("seniority", sa.String(length=40), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("duration_minutes BETWEEN 5 AND 60"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_org_id"), ["org_id"], unique=False)

    op.create_table(
        "memberships",
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('owner','recruiter','reviewer')"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "subject"),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memberships_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memberships_subject"), ["subject"], unique=False)

    op.create_table(
        "usage_records",
        sa.Column("application_id", sa.String(length=36), nullable=True),
        sa.Column("meter", sa.String(length=50), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usage_records_meter"), ["meter"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_records_org_id"), ["org_id"], unique=False)

    op.create_table(
        "applications",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("accommodation", sa.Text(), nullable=False),
        sa.Column("recording_required", sa.Boolean(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "candidate_id"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_applications_candidate_id"), ["candidate_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_org_id"), ["org_id"], unique=False)

    op.create_table(
        "campaigns",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "idempotency_key"),
    )
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_campaigns_org_id"), ["org_id"], unique=False)

    op.create_table(
        "delivery_events",
        sa.Column("delivery_id", sa.String(length=36), nullable=False),
        sa.Column("provider_event_id", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["delivery_id"], ["email_deliveries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_event_id"),
    )
    with op.batch_alter_table("delivery_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_delivery_events_org_id"), ["org_id"], unique=False)

    op.create_table(
        "job_criteria",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("anchors", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_criteria", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_criteria_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_criteria_org_id"), ["org_id"], unique=False)

    op.create_table(
        "consents",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("policy_version", sa.String(length=30), nullable=False),
        sa.Column("recording", sa.Boolean(), nullable=False),
        sa.Column("transcription", sa.Boolean(), nullable=False),
        sa.Column("ai_evaluation", sa.Boolean(), nullable=False),
        sa.Column("device_check", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id", "policy_version"),
    )
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_consents_org_id"), ["org_id"], unique=False)

    op.create_table(
        "documents",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_application_id"), ["application_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_org_id"), ["org_id"], unique=False)

    op.create_table(
        "interview_plans",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id"),
    )
    with op.batch_alter_table("interview_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interview_plans_org_id"), ["org_id"], unique=False)

    op.create_table(
        "interview_sessions",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("question_index", sa.Integer(), nullable=False),
        sa.Column("followups", sa.Integer(), nullable=False),
        sa.Column("followup_text", sa.Text(), nullable=False),
        sa.Column("turn", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audio_quality", sa.String(), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=True),
        sa.Column("connection_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id"),
    )
    with op.batch_alter_table("interview_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interview_sessions_org_id"), ["org_id"], unique=False)

    op.create_table(
        "invitations",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("last_reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invitations_application_id"), ["application_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_invitations_org_id"), ["org_id"], unique=False)

    op.create_table(
        "email_challenges",
        sa.Column("invitation_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["invitation_id"], ["invitations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_challenges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_email_challenges_org_id"), ["org_id"], unique=False)

    op.create_table(
        "evaluations",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=False),
        sa.Column("completeness", sa.String(length=80), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "version"),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evaluations_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evaluations_session_id"), ["session_id"], unique=False)

    op.create_table(
        "extractions",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("claims", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id"),
    )
    with op.batch_alter_table("extractions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_extractions_org_id"), ["org_id"], unique=False)

    op.create_table(
        "questions",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("competency", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("expected_evidence", sa.JSON(), nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=False),
        sa.Column("max_followups", sa.Integer(), nullable=False),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["interview_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "position"),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_questions_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_questions_plan_id"), ["plan_id"], unique=False)

    op.create_table(
        "recording_manifests",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("expected_clips", sa.Integer(), nullable=False),
        sa.Column("missing_sequences", sa.JSON(), nullable=False),
        sa.Column("gaps", sa.JSON(), nullable=False),
        sa.Column("finalized", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    with op.batch_alter_table("recording_manifests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recording_manifests_org_id"), ["org_id"], unique=False)

    op.create_table(
        "recording_objects",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sequence >= 0"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
        sa.UniqueConstraint("session_id", "sequence"),
    )
    with op.batch_alter_table("recording_objects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recording_objects_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recording_objects_session_id"), ["session_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("audience", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("manager_notes", sa.Text(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("audience IN ('manager','candidate')"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "audience", "version"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_session_id"), ["session_id"], unique=False)

    op.create_table(
        "rubric_versions",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=False),
        sa.Column("approved_by", sa.String(length=200), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["interview_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "version"),
    )
    with op.batch_alter_table("rubric_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rubric_versions_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rubric_versions_plan_id"), ["plan_id"], unique=False)

    op.create_table(
        "session_transitions",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("from_state", sa.String(length=30), nullable=False),
        sa.Column("to_state", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session_transitions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_transitions_org_id"), ["org_id"], unique=False)

    op.create_table(
        "video_observations",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("evidence_key", sa.String(length=500), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("video_observations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_video_observations_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_observations_session_id"), ["session_id"], unique=False)

    op.create_table(
        "answers",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("turn", sa.Integer(), nullable=False),
        sa.Column("segment_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "turn"),
    )
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_answers_org_id"), ["org_id"], unique=False)

    op.create_table(
        "transcript_segments",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("result_id", sa.String(length=150), nullable=False),
        sa.Column("speaker", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("final", sa.Boolean(), nullable=False),
        sa.Column("quality", sa.String(), nullable=False),
        sa.Column("turn", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("end_ms >= start_ms"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "result_id"),
    )
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transcript_segments_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_transcript_segments_session_id"), ["session_id"], unique=False)

    op.create_table(
        "evidence_references",
        sa.Column("evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("segment_id", sa.String(length=36), nullable=False),
        sa.Column("dimension", sa.String(length=100), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["evaluation_id"], ["evaluations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["segment_id"], ["transcript_segments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_references", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_references_org_id"), ["org_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence_references", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_references_org_id"))

    op.drop_table("evidence_references")
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_segments_session_id"))
        batch_op.drop_index(batch_op.f("ix_transcript_segments_org_id"))

    op.drop_table("transcript_segments")
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answers_org_id"))

    op.drop_table("answers")
    with op.batch_alter_table("video_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_video_observations_session_id"))
        batch_op.drop_index(batch_op.f("ix_video_observations_org_id"))

    op.drop_table("video_observations")
    with op.batch_alter_table("session_transitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_transitions_org_id"))

    op.drop_table("session_transitions")
    with op.batch_alter_table("rubric_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rubric_versions_plan_id"))
        batch_op.drop_index(batch_op.f("ix_rubric_versions_org_id"))

    op.drop_table("rubric_versions")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_session_id"))
        batch_op.drop_index(batch_op.f("ix_reports_org_id"))

    op.drop_table("reports")
    with op.batch_alter_table("recording_objects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recording_objects_session_id"))
        batch_op.drop_index(batch_op.f("ix_recording_objects_org_id"))

    op.drop_table("recording_objects")
    with op.batch_alter_table("recording_manifests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recording_manifests_org_id"))

    op.drop_table("recording_manifests")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_plan_id"))
        batch_op.drop_index(batch_op.f("ix_questions_org_id"))

    op.drop_table("questions")
    with op.batch_alter_table("extractions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extractions_org_id"))

    op.drop_table("extractions")
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluations_session_id"))
        batch_op.drop_index(batch_op.f("ix_evaluations_org_id"))

    op.drop_table("evaluations")
    with op.batch_alter_table("email_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_challenges_org_id"))

    op.drop_table("email_challenges")
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invitations_org_id"))
        batch_op.drop_index(batch_op.f("ix_invitations_application_id"))

    op.drop_table("invitations")
    with op.batch_alter_table("interview_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interview_sessions_org_id"))

    op.drop_table("interview_sessions")
    with op.batch_alter_table("interview_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interview_plans_org_id"))

    op.drop_table("interview_plans")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_org_id"))
        batch_op.drop_index(batch_op.f("ix_documents_application_id"))

    op.drop_table("documents")
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consents_org_id"))

    op.drop_table("consents")
    with op.batch_alter_table("job_criteria", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_criteria_org_id"))
        batch_op.drop_index(batch_op.f("ix_job_criteria_job_id"))

    op.drop_table("job_criteria")
    with op.batch_alter_table("delivery_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_delivery_events_org_id"))

    op.drop_table("delivery_events")
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaigns_org_id"))

    op.drop_table("campaigns")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_org_id"))
        batch_op.drop_index(batch_op.f("ix_applications_job_id"))
        batch_op.drop_index(batch_op.f("ix_applications_candidate_id"))

    op.drop_table("applications")
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_records_org_id"))
        batch_op.drop_index(batch_op.f("ix_usage_records_meter"))

    op.drop_table("usage_records")
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memberships_subject"))
        batch_op.drop_index(batch_op.f("ix_memberships_org_id"))

    op.drop_table("memberships")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_org_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("email_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_deliveries_provider_id"))
        batch_op.drop_index(batch_op.f("ix_email_deliveries_org_id"))

    op.drop_table("email_deliveries")
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidates_org_id"))

    op.drop_table("candidates")
    op.drop_table("auth_sessions")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_org_id"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("async_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_ready")
        batch_op.drop_index(batch_op.f("ix_async_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_async_jobs_org_id"))

    op.drop_table("async_jobs")
    op.drop_table("rate_buckets")
    op.drop_table("organizations")
    # ### end Alembic commands ###
