"""monthly_usage_period"""

from alembic import op
import sqlalchemy as sa

revision = "be20154950a3"
down_revision = "1dc0257e8803"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("usage_period", sa.String(length=7), nullable=False, server_default="1970-01"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_column("usage_period")

    # ### end Alembic commands ###
